name: Deploy Monorepo MFC

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4

      - name: Build e Deploy (mfc-front, mfc-back)
        run: |
          docker compose --env-file /home/actions/.env down
          docker compose --env-file /home/actions/.env up -d --build
          docker image prune -f
