name: Deploy Monorepo MFC
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4

      - name: Build e Deploy (mfc-front, mfc-back)
        run: |
          docker compose --env-file /root/MFC-My_Finance_Control/.env up -d --build
          docker image prune -f
